out_dir: results
metric_best: mrr
num_workers: 4
wandb:
  use: True
  project: pcqm4m-contact
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: SANTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layers: 4
  n_heads: 4
  dim_hidden: 100  # `gt.dim_hidden` must match `gnn.dim_inner`
  full_graph: True
  gamma: 1e-5
  dropout: 0.0
  layer_norm: False
  batch_norm: True
  residual: True
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 100  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  batch_accumulation: 1
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
