out_dir: results
metric_best: mrr
num_workers: 4
wandb:
  use: True
  project: pcqm4m-contact
dataset:
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: False
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 380
  layer_type: gcnconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
